services:
  # Frontend service
  - type: web
    name: frontend-service
    env: node
    plan: free
    buildCommand: cd frontend && npm install
    startCommand: cd frontend && npm run dev
    branch: main
    envVars:
      - key: NODE_ENV
        value: production

  # Backend service
  - type: web
    name: backend-service
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && nodemon server.js
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
